# Generated by Django 2.2.1 on 2019-09-20 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offline_Question',
            fields=[
                ('question_text', models.CharField(max_length=200)),
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('publish_date', models.DateField()),
                ('A', models.CharField(default='', max_length=200)),
                ('B', models.CharField(default='', max_length=200)),
                ('C', models.CharField(default='', max_length=200)),
                ('D', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Offline_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=200)),
                ('Value', models.CharField(max_length=200)),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Offline_Question')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
