# Generated by Django 2.2.1 on 2019-09-15 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('U', 'Upcoming'), ('L', 'Live'), ('C', 'Completed')], default='U', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField(max_length=1000)),
            ],
        ),
    ]
