# Generated by Django 2.2.1 on 2019-09-21 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Live', 'Live'), ('Completed', 'Completed')], default='U', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField(max_length=1000)),
                ('sentim', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
